### ISSUE TITLE
Expose some method of listing all chord types

### ISSUE THREAD

**Issue by secrettriangle** [saebekassebil/teoria#73]
Related: #72

**Comment by saebekassebil** [comment]
Well this is impossible/impractical. But it should be possible (and useful) to export all triad chord types (major, minor, diminished, augmented, sus2, sus4, \#5, b5)

**Comment by secrettriangle** [comment]
I understand there may be some technical difficulties with this, but I think it's worth it if it's at all possible. Someone making a music app would want to let their users pick from a list of chords, no?

**Comment by saebekassebil** [comment]
But this is not the scope of this library (which is already to wide). You should probably make a dictionary of some kind in some other module? The chords that are "hard-coded" in teoria, are chords used by the chord parser - not for listing.

**Comment by secrettriangle** [comment]
Up to you I suppose. I still think it would be useful to have a list of chords but I understand if it's too much work.

**Comment by saebekassebil** [comment]
It would certainly be useful to such people that needs such information - but I'm not one of those and since this library is for analyzing and (dynamically) generating stuff w. regards to music theory I don't think a dictionary of chord names would be valuable.

You could maybe generate a list from here:
http://en.wikibooks.org/wiki/Music_Theory/Complete_List_of_Chord_Patterns
